name: Deploy to nowhere

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  # ensure that only main branch tags are deployed to production
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run:
          echo "test"
