name: Deploy to nowhere

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  # ensure that only main branch tags are deployed to production
  deploy:
    container:
      image: node:20
    steps:
      - name: test
        run:
          echo "test"
